const CENTER_NAMES=['Ganso','Puyuhuapi 2','Puyuhuapi 1','Pearson','Delta','Arbolito','Camargo','Yelen','Yalac','Refugio'];
const REQUEST_CENTERS=[...CENTER_NAMES,'Área / Base Cisnes'];
const {version:BASE_VERSION,equipment:DEFAULT_EQUIPMENT,areaAssets:DEFAULT_AREA_ASSETS,requests:DEFAULT_REQUESTS,stock:DEFAULT_STOCK}=window.MULTIX_BASE;
const emptyCenter=()=>({novelties:'',works:'',pending:'',companies:'',observations:'',equipment:[],plants:{osmosis:{status:'Sin información',detail:''},treatment:{status:'Sin información',detail:''}},feeding:{blower:'Sin información',selectors:'Sin información',dosers:'Sin información',screw:'Sin información',vfd:'Sin información',notes:''},photos:[]});
function newReport(){const centers={};CENTER_NAMES.forEach(n=>centers[n]=emptyCenter());return {meta:{start:'',end:'',zone:'Puyuhuapi / Base Cisnes',area:'Operaciones',mechanic:''},centers,requests:[],history:[],stock:[],areaAssets:[],baseVersion:0}}
let data=load()||newReport(); let currentCenter=null;
function applyBaseData(){
  if(!data.meta)data.meta=newReport().meta;
  if(!data.centers)data.centers={};
  CENTER_NAMES.forEach(n=>{if(!data.centers[n])data.centers[n]=emptyCenter();if(!Array.isArray(data.centers[n].equipment))data.centers[n].equipment=[]});
  if(!Array.isArray(data.requests))data.requests=[];
  if(!Array.isArray(data.stock))data.stock=[];
  if(!Array.isArray(data.areaAssets))data.areaAssets=[];
  if(!Array.isArray(data.history))data.history=[];
  if((data.baseVersion||0)>=BASE_VERSION)return;
  CENTER_NAMES.forEach(n=>{(DEFAULT_EQUIPMENT[n]||[]).forEach(e=>{const exists=data.centers[n].equipment.some(x=>(x.id&&x.id===e.id)||(x.reg&&e.reg&&String(x.reg)===String(e.reg)&&String(x.name||'')===String(e.name||'')));if(!exists)data.centers[n].equipment.push(JSON.parse(JSON.stringify(e)))})});
  DEFAULT_AREA_ASSETS.forEach(e=>{if(!data.areaAssets.some(x=>(x.id&&x.id===e.id)||(x.reg&&e.reg&&String(x.reg)===String(e.reg)&&String(x.name||'')===String(e.name||''))))data.areaAssets.push(JSON.parse(JSON.stringify(e)))});
  DEFAULT_REQUESTS.forEach(r=>{const exists=data.requests.some(x=>String(x.center||'')===String(r.center||'')&&String(x.equipment||'')===String(r.equipment||'')&&String(x.material||'')===String(r.material||''));if(!exists)data.requests.push(JSON.parse(JSON.stringify(r)))});
  DEFAULT_STOCK.forEach(s=>{const existing=data.stock.find(x=>(x.id&&x.id===s.id)||(String(x.material||'').toLowerCase()===String(s.material||'').toLowerCase()&&String(x.area||'').toLowerCase()===String(s.area||'').toLowerCase()));if(!existing)data.stock.push(JSON.parse(JSON.stringify(s))) });
  data.baseVersion=BASE_VERSION;
  localStorage.setItem('multixMantencion',JSON.stringify(data));
}
function load(){try{return JSON.parse(localStorage.getItem('multixMantencion'))}catch(e){return null}}
function save(){syncMeta();localStorage.setItem('multixMantencion',JSON.stringify(data));document.getElementById('saveState').textContent='Guardado '+new Date().toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'});renderAll()}
function syncMeta(){data.meta.start=startDate.value;data.meta.end=endDate.value;data.meta.zone=zone.value;data.meta.mechanic=mechanic.value}
function init(){applyBaseData();startDate.value=data.meta.start||'';endDate.value=data.meta.end||'';zone.value=data.meta.zone||'Puyuhuapi / Base Cisnes';mechanic.value=data.meta.mechanic||'';rDate.value=new Date().toISOString().slice(0,10);rCenter.innerHTML='';REQUEST_CENTERS.forEach(n=>rCenter.add(new Option(n,n)));const areas=[...new Set(data.stock.map(s=>s.area).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));stockAreaFilter.innerHTML='<option value="">Todas las áreas</option>'+areas.map(a=>`<option value="${attr(a)}">${esc(a)}</option>`).join('');renderAll();registerSW()}
function renderAll(){renderStats();renderCenters();renderAreaAssets();renderSummary();renderFeeding();renderRequests();renderStock();renderHistory()}
function calcStats(){let equipment=0,vencidos=0,generators=0,boats=0,motocomp=0,plants=0;Object.values(data.centers).forEach(c=>{equipment+=c.equipment.length;c.equipment.forEach(e=>{if(e.status==='Vencido'||e.status==='Inoperativo')vencidos++;const t=(e.type||e.name||'').toLowerCase();if(t.includes('gener'))generators++;if(t.includes('bote'))boats++;if(t.includes('moto'))motocomp++;});Object.values(c.plants).forEach(p=>{if(p.status!=='Sin información')plants++})});return {centers:CENTER_NAMES.length,equipment,vencidos,generators,boats,motocomp,plants,requests:data.requests.length}}
function renderStats(){const s=calcStats();stats.innerHTML=[['centros',s.centers],['equipos',s.equipment],['vencidos',s.vencidos,'warn'],['generadores',s.generators],['plantas',s.plants],['solicitudes',s.requests]].map(x=>`<div class="stat ${x[2]||''}"><div class="n">${x[1]}</div><div class="l">${x[0]}</div></div>`).join('')}
function centerIssues(c){let n=c.equipment.filter(e=>['Vencido','Inoperativo'].includes(e.status)).length;Object.values(c.plants).forEach(p=>{if(p.status==='Inoperativa')n++});Object.values(c.feeding).forEach(v=>{if(v==='Inoperativo')n++});return n}
function renderCenters(){centerList.innerHTML=CENTER_NAMES.map(n=>{const c=data.centers[n],issues=centerIssues(c);const info=[c.equipment.length+' equipos'];if(c.plants.osmosis.status!=='Sin información')info.push('Ósmosis '+c.plants.osmosis.status);if(c.plants.treatment.status!=='Sin información')info.push('Tratamiento '+c.plants.treatment.status);return `<div class="center-card" onclick="openCenter('${n.replaceAll("'","\\'")}')"><h3>${n}</h3><div class="badges">${info.map(t=>`<span class="badge">${esc(t)}</span>`).join('')}${issues?`<span class="badge red">${issues} alerta${issues>1?'s':''}</span>`:'<span class="badge green">Sin alertas críticas</span>'}</div></div>`}).join('')}
function renderAreaAssets(){const rows=(data.areaAssets||[]);areaAssetList.innerHTML=rows.length?`<div class="tablewrap"><table class="area-table"><thead><tr><th>Grupo</th><th>Equipo</th><th>Actual</th><th>Últ. mant.</th><th>Próxima</th><th>Estado</th><th>Detalle</th></tr></thead><tbody>${rows.map(e=>`<tr><td>${esc(e.group||'Área')}</td><td>${esc(e.name||e.type)}</td><td>${esc(e.current||'')}</td><td>${esc(e.last||'')}</td><td>${esc(e.next||'')}</td><td class="status ${esc(e.status||'')}">${esc(e.status||'')}</td><td>${esc(e.notes||'')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sin equipos de área pendientes de asignar.</div>'}

function renderSummary(){const alerts=[];Object.entries(data.centers).forEach(([n,c])=>{if(c.novelties)alerts.push(`<div class="alert"><b>${esc(n)}</b> — ${esc(c.novelties)}</div>`)});summaryAlerts.innerHTML=alerts.length?alerts.join(''):'<div class="empty">Aún no hay novedades registradas.</div>';const att=[];Object.entries(data.centers).forEach(([n,c])=>{c.equipment.forEach(e=>{if(['Vencido','Inoperativo'].includes(e.status))att.push(`<div class="attention"><b>${esc(n)} — ${esc(e.name||e.type)}</b><div class="helper">${esc(e.status)} ${e.notes?'· '+esc(e.notes):''}</div></div>`)});Object.entries(c.plants).forEach(([k,p])=>{if(p.status==='Inoperativa')att.push(`<div class="attention"><b>${esc(n)} — ${k==='osmosis'?'Planta de Ósmosis':'Planta de Tratamiento'}</b><div class="helper">${esc(p.detail)}</div></div>`)})});attentionList.innerHTML=att.length?att.join(''):'<div class="empty">No hay equipos marcados como vencidos o inoperativos.</div>'}
function renderFeeding(){feedingList.innerHTML=CENTER_NAMES.map(n=>{const f=data.centers[n].feeding;const vals=[['Blower',f.blower],['Selectoras',f.selectors],['Doser',f.dosers],['Tornillo',f.screw],['VFD',f.vfd]].filter(x=>x[1]!=='Sin información');if(!vals.length&&!f.notes)return '';return `<div class="panel"><h2>${n}</h2><div class="badges">${vals.map(x=>`<span class="badge ${x[1]==='Inoperativo'?'red':x[1]==='En observación'?'orange':'green'}">${x[0]}: ${x[1]}</span>`).join('')}</div>${f.notes?`<p class="helper">${esc(f.notes)}</p>`:''}</div>`}).join('')||'<div class="empty">Sin información de alimentación todavía.</div>'}
function renderRequests(){requestTable.innerHTML=data.requests.map((r,i)=>`<tr><td>${esc(r.center)}</td><td>${esc(r.equipment)}</td><td>${esc(r.material)}${r.notes?`<div class="helper">${esc(r.notes)}</div>`:''}</td><td>${esc(r.requestedTo)}</td><td>${esc(r.date)}</td><td class="status ${esc(r.status)}">${esc(r.status)}</td><td><button class="btn small danger" onclick="delRequest(${i})">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Sin solicitudes</td></tr>'}

function stockTotal(s){const a=Number(s.initial)||0,b=Number(s.in)||0,c=Number(s.out)||0;return a+b-c}
function renderStock(){if(!Array.isArray(data.stock))data.stock=[];data.stock.forEach(s=>s.total=stockTotal(s));const q=(stockSearch?.value||'').trim().toLowerCase(),area=stockAreaFilter?.value||'';const filtered=data.stock.filter(s=>(!area||s.area===area)&&(!q||(`${s.material} ${s.area} ${s.destination||''}`).toLowerCase().includes(q)));const zero=data.stock.filter(s=>stockTotal(s)<=0).length,low=data.stock.filter(s=>stockTotal(s)>0&&stockTotal(s)<=2).length;stockSummary.innerHTML=`<span class="badge">${data.stock.length} repuestos/materiales</span><span class="badge orange">${low} stock bajo</span><span class="badge red">${zero} sin stock</span><span class="badge">${filtered.length} visibles</span>`;stockList.innerHTML=filtered.map(s=>{const t=stockTotal(s),cls=t<=0?'zero':t<=2?'low':'';return `<div class="stock-item"><div class="stock-head"><div><div class="stock-title">${esc(s.material)}</div><div class="badges"><span class="badge">${esc(s.area)}</span>${s.destination?`<span class="badge orange">Destino: ${esc(s.destination)}</span>`:''}</div></div><div class="stock-total ${cls}">${t}</div></div><div class="stock-grid"><div><label>Cant. inicial</label><input type="number" step="1" data-stock="${s.id}" data-k="initial" value="${attr(s.initial)}"></div><div><label>Entradas</label><input type="number" step="1" data-stock="${s.id}" data-k="in" value="${attr(s.in)}"></div><div><label>Salidas</label><input type="number" step="1" data-stock="${s.id}" data-k="out" value="${attr(s.out)}"></div><div><label>Destino</label><input data-stock="${s.id}" data-k="destination" value="${attr(s.destination||'')}" placeholder="Centro / destino"></div></div></div>`}).join('')||'<div class="empty">No hay resultados para ese filtro.</div>'}
function handleStockChange(e){const id=e.target?.dataset?.stock,k=e.target?.dataset?.k;if(!id||!k)return;const s=data.stock.find(x=>x.id===id);if(!s)return;s[k]=['initial','in','out'].includes(k)?(Number(e.target.value)||0):e.target.value;s.total=stockTotal(s);localStorage.setItem('multixMantencion',JSON.stringify(data));renderStock()}

function renderHistory(){const h=data.history||[];historyList.innerHTML=(h.length?h.map((x,i)=>`<div class="history-item"><div><b>${esc(x.meta.start||'Sin fecha')} → ${esc(x.meta.end||'Sin fecha')}</b><div class="helper">${esc(x.meta.mechanic||'')} · ${x.requests?.length||0} solicitudes</div></div><button class="btn small" onclick="restoreHistory(${i})">Abrir</button></div>`).join(''):'<div class="empty">Todavía no hay informes archivados.</div>')+`<div class="btnrow"><button class="btn" onclick="backupJSON()">Respaldar datos</button><button class="btn" onclick="restoreInput.click()">Cargar respaldo</button></div>`}
function openCenter(name){currentCenter=name;const c=data.centers[name];editorTitle.textContent=name;cNov.value=c.novelties;cWorks.value=c.works;cPending.value=c.pending;cCompanies.value=c.companies;cObs.value=c.observations;osmosisStatus.value=c.plants.osmosis.status;osmosisDetail.value=c.plants.osmosis.detail;treatmentStatus.value=c.plants.treatment.status;treatmentDetail.value=c.plants.treatment.detail;fBlower.value=c.feeding.blower;fSelectors.value=c.feeding.selectors;fDosers.value=c.feeding.dosers;fScrew.value=c.feeding.screw;fVfd.value=c.feeding.vfd;fNotes.value=c.feeding.notes;renderEqEditor();renderPhotos();editor.classList.add('open')}
function closeCenter(){editor.classList.remove('open')}
function renderEqEditor(){const c=data.centers[currentCenter];equipmentEditor.innerHTML=c.equipment.map((e,i)=>`<div class="eqrow"><input data-i="${i}" data-k="name" value="${attr(e.name)}" placeholder="Equipo"><input data-i="${i}" data-k="current" value="${attr(e.current)}" placeholder="Actual"><input data-i="${i}" data-k="last" value="${attr(e.last)}" placeholder="Últ. mant."><input data-i="${i}" data-k="next" value="${attr(e.next)}" placeholder="Próxima"><select data-i="${i}" data-k="status"><option${sel(e.status,'OK')}>OK</option><option${sel(e.status,'Próximo')}>Próximo</option><option${sel(e.status,'Vencido')}>Vencido</option><option${sel(e.status,'Operativo')}>Operativo</option><option${sel(e.status,'Inoperativo')}>Inoperativo</option><option${sel(e.status,'En observación')}>En observación</option></select><button class="btn small danger" onclick="delEq(${i})">×</button><input data-i="${i}" data-k="type" value="${attr(e.type)}" placeholder="Tipo (Generador, Bote...)" style="grid-column:1/3"><input data-i="${i}" data-k="reg" value="${attr(e.reg)}" placeholder="N° registro" style="grid-column:3/4"><input data-i="${i}" data-k="notes" value="${attr(e.notes)}" placeholder="Observaciones" style="grid-column:4/6"></div>`).join('')||'<div class="empty">Sin equipos registrados en este centro.</div>'}
function collectEq(){document.querySelectorAll('#equipmentEditor [data-i]').forEach(el=>{const i=+el.dataset.i,k=el.dataset.k;data.centers[currentCenter].equipment[i][k]=el.value})}
function delEq(i){collectEq();data.centers[currentCenter].equipment.splice(i,1);renderEqEditor()}
function renderPhotos(){const c=data.centers[currentCenter];photoGrid.innerHTML=c.photos.map((p,i)=>`<div class="photo"><img src="${p.data}" alt="Foto"><button onclick="delPhoto(${i})">×</button></div>`).join('')}
function delPhoto(i){data.centers[currentCenter].photos.splice(i,1);renderPhotos()}
async function addPhotos(files){for(const f of files){const dataUrl=await compressImage(f);data.centers[currentCenter].photos.push({name:f.name,data:dataUrl})}renderPhotos()}
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),r=new FileReader();r.onload=e=>{img.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72))};img.src=e.target.result};r.onerror=reject;r.readAsDataURL(file)})}
function saveCurrentCenter(){collectEq();const c=data.centers[currentCenter];c.novelties=cNov.value;c.works=cWorks.value;c.pending=cPending.value;c.companies=cCompanies.value;c.observations=cObs.value;c.plants.osmosis={status:osmosisStatus.value,detail:osmosisDetail.value};c.plants.treatment={status:treatmentStatus.value,detail:treatmentDetail.value};c.feeding={blower:fBlower.value,selectors:fSelectors.value,dosers:fDosers.value,screw:fScrew.value,vfd:fVfd.value,notes:fNotes.value};save();closeCenter()}
function delRequest(i){data.requests.splice(i,1);save()}
function restoreHistory(i){const h=data.history||[];if(!h[i])return;if(confirm('¿Abrir este informe? El informe actual se reemplazará, pero seguirá archivado.')){const hist=data.history;data=JSON.parse(JSON.stringify(h[i]));data.history=hist;save();init();switchTab('summary')}}
function newWeekly(){syncMeta();const snapshot=JSON.parse(JSON.stringify({...data,history:undefined}));data.history=data.history||[];data.history.unshift(snapshot);const hist=data.history;const old=data;data=newReport();data.history=hist;data.meta.zone=snapshot.meta.zone;data.meta.mechanic=snapshot.meta.mechanic;data.stock=old.stock||[];data.areaAssets=old.areaAssets||[];data.requests=old.requests||[];data.baseVersion=old.baseVersion||BASE_VERSION;CENTER_NAMES.forEach(n=>{const prev=old.centers?.[n];if(!prev)return;data.centers[n].equipment=JSON.parse(JSON.stringify(prev.equipment||[]));data.centers[n].plants=JSON.parse(JSON.stringify(prev.plants||data.centers[n].plants));data.centers[n].feeding=JSON.parse(JSON.stringify(prev.feeding||data.centers[n].feeding));data.centers[n].pending=prev.pending||''});save();init();switchTab('summary')}
function backupJSON(){syncMeta();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='multix-mantencion-respaldo.json';a.click();URL.revokeObjectURL(a.href)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function attr(s=''){return esc(s)}function sel(a,b){return a===b?' selected':''}
function switchTab(id){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===id));document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===id))}
function registerSW(){}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>switchTab(t.dataset.tab));saveBtn.onclick=save;pdfBtn.onclick=()=>{save();buildPrint();setTimeout(()=>window.print(),150)};newBtn.onclick=()=>{if(confirm('Se archivará el informe actual y se creará uno nuevo. ¿Continuar?'))newWeekly()};closeEditor.onclick=closeCenter;saveCenter.onclick=saveCurrentCenter;addEquipment.onclick=()=>{collectEq();data.centers[currentCenter].equipment.push({name:'',type:'',current:'',last:'',next:'',reg:'',status:'OK',notes:''});renderEqEditor()};photoInput.onchange=e=>addPhotos([...e.target.files]).then(()=>e.target.value='');addRequest.onclick=()=>{data.requests.push({id:'req-user-'+Date.now(),center:rCenter.value,equipment:rEquip.value,material:rMaterial.value,requestedTo:rTo.value,date:rDate.value,status:rStatus.value,notes:''});rEquip.value=rMaterial.value=rTo.value='';save()};restoreInput.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{try{const parsed=JSON.parse(ev.target.result);if(!parsed.centers)throw 0;data=parsed;save();init();alert('Respaldo cargado correctamente.')}catch(_){alert('El archivo no corresponde a un respaldo válido.')}};r.readAsText(f);e.target.value=''};[startDate,endDate,zone,mechanic].forEach(el=>el.addEventListener('change',save));stockSearch.addEventListener('input',renderStock);stockAreaFilter.addEventListener('change',renderStock);stockList.addEventListener('change',handleStockChange);saveStockBtn.onclick=()=>{localStorage.setItem('multixMantencion',JSON.stringify(data));saveState.textContent='Stock guardado '+new Date().toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'});renderStock()};init();
