// MultiX v10 — vista de informe + PDF móvil, sin alertas de mantención dentro del informe
(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const has=v=>String(v??'').trim().length>0;
  const isIOS=()=>/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);

  function loadScript(src,id){
    if(document.getElementById(id))return Promise.resolve();
    return new Promise((resolve,reject)=>{const s=document.createElement('script');s.id=id;s.src=src;s.async=false;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});
  }
  async function loadDependencies(){
    try{await loadScript('overrides-v6.js?v=10','mxOverridesV6Loader');}catch(e){console.warn('No se pudo cargar overrides-v6',e);}
    try{await loadScript('active-v9.js?v=10','mxActiveV9Loader');}catch(e){console.warn('No se pudo cargar active-v9',e);}
  }

  function state(){return typeof data!=='undefined'?data:null;}
  function activeNames(){
    const d=state();
    if(typeof window.mxGetActiveCenters==='function')return window.mxGetActiveCenters().filter(n=>d?.centers?.[n]);
    const a=Array.isArray(window.MX_ACTIVE_CENTERS)?window.MX_ACTIVE_CENTERS:['Ganso','Puyuhuapi 2','Pearson','Arbolito','Delta'];
    return a.filter(n=>d?.centers?.[n]);
  }
  function meaningful(name,c){
    if(typeof window.mxMeaningfulCenter==='function')return !!window.mxMeaningfulCenter(name,c);
    if(!c)return false;
    if(has(c.novelties)||has(c.works)||has(c.pending)||has(c.companies)||has(c.observations)||(c.photos||[]).length)return true;
    const p=c.plants||{};if(['osmosis','treatment'].some(k=>has(p[k]?.detail)||(p[k]?.status&&p[k].status!=='Sin información')))return true;
    const f=c.feeding||{};if(has(f.notes)||['blower','selectors','dosers','screw','vfd'].some(k=>f[k]&&f[k]!=='Sin información'))return true;
    return (state()?.requests||[]).some(r=>r.center===name&&String(r.id||'').startsWith('req-user-'));
  }
  function reportNames(){const d=state();return activeNames().filter(n=>meaningful(n,d?.centers?.[n]));}

  function parseHours(v){const raw=String(v??'').trim();if(!raw||raw==='-')return null;const n=Number(raw.replace(/\s/g,'').replace(/\./g,'').replace(',','.'));return Number.isFinite(n)?n:null;}
  function intervalFor(e){const t=((e?.type||'')+' '+(e?.name||'')).toLowerCase();if(t.includes('generador'))return 250;if(t.includes('bote fb')||t.includes('motor fuera')||t.includes('fuera borda'))return 300;return null;}
  function recalc(e){
    if(typeof window.mxRecalcEquipment==='function'){try{window.mxRecalcEquipment(e);return;}catch(_){} }
    const int=intervalFor(e),last=parseHours(e?.last),cur=parseHours(e?.current);if(int!==null&&last!==null)e.next=String(last+int);const next=parseHours(e?.next);if(!['Inoperativo','En observación'].includes(e?.status)&&cur!==null&&next!==null)e.status=cur>=next?'Vencido':(next-cur<=50?'Próximo':'OK');
  }
  function fmt(v){const n=parseHours(v);return n===null?'Sin dato':new Intl.NumberFormat('es-CL',{maximumFractionDigits:1}).format(n)+' h';}
  function persist(){try{if(typeof window.mxPersistDraft==='function')return window.mxPersistDraft(true);if(typeof syncMeta==='function')syncMeta();const d=state();if(d)localStorage.setItem('multixMantencion',JSON.stringify(d));}catch(_){} }

  function photoMatches(p,e,i){if(p?.targetType!=='equipment')return false;const key='equipment:'+(e.id||('idx-'+i));return p.targetKey===key||(p.targetId&&e.id&&p.targetId===e.id)||(p.targetName&&p.targetName===(e.name||e.type));}
  const compPhotos=(photos,id)=>photos.filter(p=>p?.targetType==='component'&&p?.targetId===id);
  const genPhotos=photos=>photos.filter(p=>!p?.targetType||p.targetType==='general');

  function installStyles(){
    if($('mxReportV10Styles'))return;
    const st=document.createElement('style');st.id='mxReportV10Styles';st.textContent=`
      .mx-report-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.mx-report-toolbar .btn{min-width:130px}
      .mx-report-status{background:#0a1924;border:1px solid var(--line);border-radius:12px;padding:12px 14px;margin-bottom:13px;color:var(--muted);font-size:12px;line-height:1.45}.mx-report-status b{color:var(--teal)}
      .mx-report-sheet-wrap{overflow:auto;padding:2px 0 28px}.mx-report-sheet{width:min(100%,850px);margin:0 auto;background:#fff;color:#172033;border-radius:16px;padding:30px 32px;box-shadow:0 8px 30px rgba(0,0,0,.28);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;line-height:1.4}
      .mx-report-brand{font-weight:850;letter-spacing:4px;font-size:18px;margin-bottom:12px}.mx-report-sheet .pr-title{font-size:28px;line-height:1.08;margin:0;color:#172033;font-weight:850}.mx-report-sheet .pr-sub{font-size:14px;color:#566171;margin:5px 0 18px}
      .mx-report-sheet .pr-meta{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;border-bottom:3px solid #172033;padding-bottom:15px;margin-bottom:22px;font-size:13px}.mx-report-sheet .pr-meta b{display:block;color:#778191;font-size:10px;letter-spacing:.6px;text-transform:uppercase;margin-bottom:5px}
      .mx-report-sheet .pr-center{margin:0 0 26px}.mx-report-sheet .pr-center h2{font-size:19px;line-height:1.2;margin:0 0 15px;padding:10px 13px;background:#f2f4f6;border-radius:8px;color:#172033}.mx-report-sheet .pr-section{margin:13px 0}.mx-report-sheet .pr-section h3{font-size:13px;color:#0a8790;text-transform:uppercase;letter-spacing:.5px;margin:0 0 7px}.mx-report-sheet .pr-section p{font-size:14px;color:#3f4a5b;line-height:1.45;margin:4px 0;white-space:pre-wrap}
      .mx-report-sheet .pr-table{width:100%;border-collapse:collapse;table-layout:fixed;margin:6px 0 11px}.mx-report-sheet .pr-table th{font-size:9px;text-transform:uppercase;color:#778191;text-align:left;padding:7px 5px;border-bottom:1px solid #ccd4db}.mx-report-sheet .pr-table td{font-size:11px;vertical-align:top;padding:8px 5px;border-bottom:1px solid #e0e5e9;color:#283444;word-break:break-word}.mx-report-sheet .pr-equipment{margin-bottom:14px}
      .mx-report-sheet .pr-photo-section{margin:9px 0 16px}.mx-report-sheet .pr-photo-section h4{font-size:11px;text-transform:uppercase;color:#0a8790;margin:0 0 7px}.mx-report-sheet .pr-photos{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.mx-report-sheet .pr-photos figure{margin:0;background:#f5f6f7;border-radius:9px;overflow:hidden}.mx-report-sheet .pr-photos img{display:block;width:100%;height:210px;object-fit:cover}.mx-report-sheet .pr-photos figcaption{font-size:10px;color:#596474;padding:7px 8px}.mx-report-sheet small{font-size:9px;color:#6a7481}.mx-report-empty{padding:28px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:14px}
      @media(max-width:760px){.mx-report-toolbar .btn{flex:1}.mx-report-sheet{padding:20px 18px;border-radius:14px}.mx-report-sheet .pr-title{font-size:23px}.mx-report-sheet .pr-meta{grid-template-columns:1fr 1fr;gap:11px;font-size:12px}.mx-report-sheet .pr-center h2{font-size:17px}.mx-report-sheet .pr-section p{font-size:13px}.mx-report-sheet .pr-table th{font-size:8px;padding:6px 3px}.mx-report-sheet .pr-table td{font-size:9px;padding:7px 3px}.mx-report-sheet .pr-photos{grid-template-columns:1fr}.mx-report-sheet .pr-photos img{height:auto;max-height:300px}}
    `;document.head.appendChild(st);
  }
  function photoBlock(list,title){if(!list?.length)return'';return `<div class="pr-photo-section"><h4>${esc(title)}</h4><div class="pr-photos">${list.map(p=>`<figure><img src="${p.data}" alt="Foto"><figcaption>${esc(p.component||p.targetName||'')}</figcaption></figure>`).join('')}</div></div>`;}
  function textBlock(title,text){return has(text)?`<div class="pr-section"><h3>${esc(title)}</h3><p>${esc(text)}</p></div>`:'';}

  function buildHTML(){
    const d=state();if(!d)return'';try{if(typeof syncMeta==='function')syncMeta();}catch(_){}
    const m=d.meta||{},parts=[];
    parts.push(`<div class="mx-report-brand">MULTI X</div><h1 class="pr-title">INFORME TÉCNICO SEMANAL DE MANTENCIÓN</h1><div class="pr-sub">Área Mantención – ${esc(m.zone||'Puyuhuapi / Base Cisnes')}</div><div class="pr-meta"><div><b>FECHA</b>${esc(m.end||'Sin fecha')}</div><div><b>PERIODO</b>${esc(m.start||'Sin fecha')} al ${esc(m.end||'Sin fecha')}</div><div><b>ÁREA</b>${esc(m.area||'Operaciones')}</div><div><b>MECÁNICO EN EL ÁREA</b>${esc(m.mechanic||'-')}</div></div>`);
    reportNames().forEach(name=>{
      const c=d.centers[name],photos=c.photos||[];parts.push(`<div class="pr-center"><h2>${esc(name.toUpperCase())}</h2>`);parts.push(textBlock('Novedades',c.novelties),textBlock('Trabajos realizados',c.works));
      if((c.equipment||[]).length){parts.push('<div class="pr-section"><h3>Equipos</h3>');c.equipment.forEach((e,i)=>{recalc(e);parts.push(`<div class="pr-equipment"><table class="pr-table"><thead><tr><th>Equipo</th><th>Actual</th><th>Últ. mant.</th><th>Próxima</th><th>Estado</th></tr></thead><tbody><tr><td><b>${esc(e.name||e.type||'Equipo')}</b>${e.reg?`<br><small>N° registro: ${esc(e.reg)}</small>`:''}${e.notes?`<br><small>${esc(e.notes)}</small>`:''}</td><td>${esc(fmt(e.current))}</td><td>${esc(fmt(e.last))}</td><td>${esc(fmt(e.next))}</td><td>${esc(e.status||'')}</td></tr></tbody></table>${photoBlock(photos.filter(p=>photoMatches(p,e,i)),'Fotografías — '+(e.name||e.type||'Equipo'))}</div>`);});parts.push('</div>');}
      const os=compPhotos(photos,'osmosis'),tr=compPhotos(photos,'treatment'),plant=[];if(c.plants?.treatment?.status&&c.plants.treatment.status!=='Sin información')plant.push(`<b>Planta de Tratamiento de Aguas Negras:</b> ${esc(c.plants.treatment.status)}${c.plants.treatment.detail?' — '+esc(c.plants.treatment.detail):''}`);if(c.plants?.osmosis?.status&&c.plants.osmosis.status!=='Sin información')plant.push(`<b>Planta de Ósmosis:</b> ${esc(c.plants.osmosis.status)}${c.plants.osmosis.detail?' — '+esc(c.plants.osmosis.detail):''}`);if(plant.length||os.length||tr.length)parts.push(`<div class="pr-section"><h3>Plantas</h3>${plant.length?`<p>${plant.join('<br>')}</p>`:''}${photoBlock(tr,'Fotografías — Planta de Tratamiento de Aguas Negras')}${photoBlock(os,'Fotografías — Planta de Ósmosis')}</div>`);
      const f=c.feeding||{},fp=compPhotos(photos,'feeding'),fv=[['Blower',f.blower],['Selectoras',f.selectors],['Doser',f.dosers],['Tornillo',f.screw],['Variadores',f.vfd]].filter(x=>x[1]&&x[1]!=='Sin información');if(fv.length||has(f.notes)||fp.length)parts.push(`<div class="pr-section"><h3>Sistema de alimentación</h3>${fv.length||has(f.notes)?`<p>${fv.map(x=>esc(x[0]+': '+x[1])).join(' · ')}${has(f.notes)?'<br>'+esc(f.notes):''}</p>`:''}${photoBlock(fp,'Fotografías — Sistema de Alimentación')}</div>`);
      parts.push(textBlock('Trabajos pendientes',c.pending),textBlock('Empresas en terreno',c.companies),textBlock('Observaciones',c.observations));
      const other=photos.filter(p=>p.targetType==='component'&&!['osmosis','treatment','feeding'].includes(p.targetId)),groups={};other.forEach(p=>{const k=p.targetName||'Componente';(groups[k]||(groups[k]=[])).push(p)});Object.entries(groups).forEach(([k,v])=>parts.push(photoBlock(v,'Fotografías — '+k)));parts.push(photoBlock(genPhotos(photos),'Fotografías generales del centro'));
      const req=(d.requests||[]).filter(r=>r.center===name);if(req.length)parts.push(`<div class="pr-section"><h3>Solicitudes y requerimientos</h3><table class="pr-table"><thead><tr><th>Equipo</th><th>Material / repuesto</th><th>Solicitado a</th><th>Fecha</th><th>Estado</th></tr></thead><tbody>${req.map(r=>`<tr><td>${esc(r.equipment||'')}</td><td>${esc(r.material||'')}</td><td>${esc(r.requestedTo||'')}</td><td>${esc(r.date||'')}</td><td>${esc(r.status||'')}</td></tr>`).join('')}</tbody></table></div>`);parts.push('</div>');
    });return parts.join('');
  }
  window.mxBuildReportHTML=buildHTML;

  function renderPreview(){persist();const host=$('mxReportPreview'),status=$('mxReportPreviewStatus');if(!host)return;const html=buildHTML(),names=reportNames();host.innerHTML=html?`<div class="mx-report-sheet">${html}</div>`:'<div class="mx-report-empty">Aún no hay información semanal para mostrar en el informe.</div>';if(status){const d=state(),photos=names.reduce((n,name)=>n+(d?.centers?.[name]?.photos?.length||0),0),now=new Date().toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'});status.innerHTML=`<b>Informe de avance semanal</b> · ${esc(d?.meta?.start||'Sin fecha')} → ${esc(d?.meta?.end||'Sin fecha')} · ${names.length} centro${names.length===1?'':'s'} incluido${names.length===1?'':'s'} · ${photos} foto${photos===1?'':'s'} · actualizado ${now}. Las alertas de mantención se muestran solo en la aplicación y no forman parte del informe.`;}}
  window.mxRenderReportPreview=renderPreview;

  function installPreview(){
    installStyles();if($('mxReportTab'))return;const tabs=document.querySelector('.tabs');if(!tabs)return;const tab=document.createElement('button');tab.className='tab';tab.id='mxReportTab';tab.dataset.tab='report';tab.textContent='Informe';const history=tabs.querySelector('[data-tab="history"]');history?tabs.insertBefore(tab,history):tabs.appendChild(tab);const section=document.createElement('section');section.className='section';section.id='report';section.innerHTML=`<div class="panel"><div class="mx-report-toolbar"><button class="btn" id="mxRefreshReport">Actualizar vista</button><button class="btn" id="mxCopyReport">Copiar texto</button><button class="btn primary" id="mxCreatePdfFromPreview">Crear PDF</button></div><div class="mx-report-status" id="mxReportPreviewStatus"><b>Informe de avance semanal.</b> Aquí se muestran solamente los centros activos que tienen información cargada esta semana.</div></div><div class="mx-report-sheet-wrap" id="mxReportPreview"></div>`;const hs=$('history');hs?.parentNode?.insertBefore(section,hs);tab.onclick=()=>{persist();if(typeof switchTab==='function')switchTab('report');setTimeout(renderPreview,30);};$('mxRefreshReport').onclick=renderPreview;$('mxCopyReport').onclick=()=>{renderPreview();const sheet=document.querySelector('#mxReportPreview .mx-report-sheet');if(!sheet)return;const text=sheet.innerText.trim();navigator.clipboard?.writeText(text).then(()=>alert('Texto del informe copiado.')).catch(()=>alert('No se pudo copiar el texto.'));};$('mxCreatePdfFromPreview').onclick=()=>window.mxCreatePdfNative();
  }

  let libPromise=null;function loadJsPDF(){if(window.jspdf?.jsPDF)return Promise.resolve(window.jspdf.jsPDF);if(libPromise)return libPromise;libPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';s.async=true;s.onload=()=>window.jspdf?.jsPDF?resolve(window.jspdf.jsPDF):reject(new Error('No se pudo iniciar el generador PDF'));s.onerror=()=>reject(new Error('No se pudo cargar el generador PDF'));document.head.appendChild(s);});return libPromise;}

  async function createPdf(){
    persist();let viewer=null;const btn=$('pdfBtn'),pb=$('mxCreatePdfFromPreview');if(isIOS()){try{viewer=window.open('','_blank');if(viewer){viewer.document.write('<!doctype html><meta name="viewport" content="width=device-width"><body style="font-family:-apple-system;padding:30px;color:#222">Generando informe PDF…</body>');viewer.document.close();}}catch(_){viewer=null;}}
    try{
      if(btn){btn.disabled=true;btn.textContent='Creando PDF…';}if(pb){pb.disabled=true;pb.textContent='Creando PDF…';}
      const jsPDF=await loadJsPDF(),pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true}),d=state();if(!d)throw new Error('No se encontraron datos del informe');try{if(typeof syncMeta==='function')syncMeta();}catch(_){}
      const names=reportNames();if(!names.length)throw new Error('Todavía no hay información semanal en centros activos para incluir');
      const W=210,H=297,L=14,R=14,T=14,B=15,CW=W-L-R,black=[24,32,45],muted=[91,102,116],teal=[16,128,140],line=[220,225,230];let y=T;const color=c=>pdf.setTextColor(...c);const addPage=()=>{pdf.addPage();y=T;pdf.setFont('helvetica','bold');pdf.setFontSize(8);color(muted);pdf.text('MULTI X · Informe Técnico Semanal de Mantención',L,8);};const ensure=h=>{if(y+h>H-B)addPage();};const para=(text,size=9,indent=0)=>{if(!has(text))return;pdf.setFont('helvetica','normal');pdf.setFontSize(size);color(muted);const lines=pdf.splitTextToSize(String(text),CW-indent),lh=size*.42+1.3;for(const ln of lines){ensure(lh+1);pdf.text(ln,L+indent,y);y+=lh;}y+=1.5;};const section=t=>{ensure(8);pdf.setFont('helvetica','bold');pdf.setFontSize(9);color(teal);pdf.text(String(t).toUpperCase(),L,y);y+=5;};const centerTitle=n=>{ensure(12);pdf.setFillColor(242,244,246);pdf.roundedRect(L,y-1,CW,9,2,2,'F');pdf.setFont('helvetica','bold');pdf.setFontSize(12);color(black);pdf.text(String(n).toUpperCase(),L+4,y+5);y+=13;};
      const eqCard=e=>{recalc(e);ensure(18);pdf.setDrawColor(...line);pdf.roundedRect(L,y,CW,16,1.5,1.5,'S');pdf.setFont('helvetica','bold');pdf.setFontSize(9);color(black);pdf.text(String(e.name||e.type||'Equipo'),L+3,y+5);pdf.setFont('helvetica','normal');pdf.setFontSize(7.5);color(muted);pdf.text(`Actual: ${fmt(e.current)}   |   Últ. mant.: ${fmt(e.last)}   |   Próxima: ${fmt(e.next)}   |   Estado: ${e.status||''}`,L+3,y+10,{maxWidth:CW-6});if(e.reg)pdf.text(`Serie / registro: ${String(e.reg)}`,L+3,y+14,{maxWidth:CW-6});y+=19;if(e.notes)para(e.notes,7.5,2);};
      const photosBlock=(list,title)=>{if(!list?.length)return;section(title);const gap=4,col=(CW-gap)/2,maxH=52;for(let i=0;i<list.length;i+=2){ensure(maxH+12);list.slice(i,i+2).forEach((p,j)=>{const x=L+j*(col+gap);try{const prop=pdf.getImageProperties(p.data),r=prop.width/prop.height;let w=col,h=w/r;if(h>maxH){h=maxH;w=h*r;}pdf.addImage(p.data,'JPEG',x,y,w,h,undefined,'FAST');pdf.setFont('helvetica','normal');pdf.setFontSize(7);color(muted);pdf.text(String(p.component||p.targetName||'').slice(0,80),x,y+h+4,{maxWidth:col});}catch(_){pdf.rect(x,y,col,35);pdf.setFontSize(7);color(muted);pdf.text('No se pudo insertar esta fotografía',x+2,y+5,{maxWidth:col-4});}});y+=maxH+8;}y+=1;};

      pdf.setFont('helvetica','bold');pdf.setFontSize(11);color(black);pdf.text('MULTI X',L,y);y+=7;pdf.setFontSize(18);pdf.text('INFORME TÉCNICO SEMANAL',L,y);y+=7;pdf.text('DE MANTENCIÓN',L,y);y+=7;pdf.setFont('helvetica','normal');pdf.setFontSize(9);color(muted);pdf.text(`Área Mantención – ${d.meta?.zone||'Puyuhuapi / Base Cisnes'}`,L,y);y+=8;pdf.setDrawColor(25,38,52);pdf.line(L,y,W-R,y);y+=6;const meta=[['FECHA',d.meta?.end||'-'],['PERIODO',`${d.meta?.start||'-'} al ${d.meta?.end||'-'}`],['ÁREA',d.meta?.area||'Operaciones'],['MECÁNICO',d.meta?.mechanic||'-']];meta.forEach(([k,v],i)=>{const x=L+(i%2)*(CW/2),yy=y+Math.floor(i/2)*13;pdf.setFont('helvetica','bold');pdf.setFontSize(7);color(muted);pdf.text(k,x,yy);pdf.setFont('helvetica','normal');pdf.setFontSize(9);color(black);pdf.text(String(v),x,yy+5,{maxWidth:CW/2-4});});y+=28;

      names.forEach(name=>{const c=d.centers[name],photos=c.photos||[];centerTitle(name);if(has(c.novelties)){section('Novedades');para(c.novelties);}if(has(c.works)){section('Trabajos realizados');para(c.works);}if((c.equipment||[]).length){section('Equipos');c.equipment.forEach((e,i)=>{eqCard(e);photosBlock(photos.filter(p=>photoMatches(p,e,i)),'Fotografías — '+(e.name||e.type||'Equipo'));});}const plant=[];if(c.plants?.treatment?.status&&c.plants.treatment.status!=='Sin información')plant.push(`Planta de Tratamiento de Aguas Negras: ${c.plants.treatment.status}${c.plants.treatment.detail?' — '+c.plants.treatment.detail:''}`);if(c.plants?.osmosis?.status&&c.plants.osmosis.status!=='Sin información')plant.push(`Planta de Ósmosis: ${c.plants.osmosis.status}${c.plants.osmosis.detail?' — '+c.plants.osmosis.detail:''}`);if(plant.length){section('Plantas');plant.forEach(para);}photosBlock(compPhotos(photos,'treatment'),'Fotografías — Planta de Tratamiento de Aguas Negras');photosBlock(compPhotos(photos,'osmosis'),'Fotografías — Planta de Ósmosis');const f=c.feeding||{},fv=[['Blower',f.blower],['Selectoras',f.selectors],['Doser',f.dosers],['Tornillo',f.screw],['Variadores',f.vfd]].filter(x=>x[1]&&x[1]!=='Sin información');if(fv.length||has(f.notes)){section('Sistema de alimentación');para(fv.map(x=>x[0]+': '+x[1]).join(' · ')+(has(f.notes)?'\n'+f.notes:''));}photosBlock(compPhotos(photos,'feeding'),'Fotografías — Sistema de Alimentación');if(has(c.pending)){section('Trabajos pendientes');para(c.pending);}if(has(c.companies)){section('Empresas en terreno');para(c.companies);}if(has(c.observations)){section('Observaciones');para(c.observations);}const other=photos.filter(p=>p.targetType==='component'&&!['osmosis','treatment','feeding'].includes(p.targetId)),groups={};other.forEach(p=>{const k=p.targetName||'Componente';(groups[k]||(groups[k]=[])).push(p)});Object.entries(groups).forEach(([k,v])=>photosBlock(v,'Fotografías — '+k));photosBlock(genPhotos(photos),'Fotografías generales del centro');const req=(d.requests||[]).filter(r=>r.center===name);if(req.length){section('Solicitudes y requerimientos');req.forEach(r=>para(`${r.equipment||'Equipo'} — ${r.material||''} — ${r.status||''}${r.requestedTo?' — Solicitado a: '+r.requestedTo:''}`,8.2));}y+=3;});
      const total=pdf.getNumberOfPages();for(let p=1;p<=total;p++){pdf.setPage(p);pdf.setFont('helvetica','normal');pdf.setFontSize(7);color(muted);pdf.text(`Página ${p} de ${total}`,W-R,H-7,{align:'right'});}const filename=`Informe_Mantencion_MultiX_${(d.meta?.end||new Date().toISOString().slice(0,10)).replaceAll('/','-')}.pdf`,blob=pdf.output('blob'),url=URL.createObjectURL(blob);if(viewer&&!viewer.closed)viewer.location.replace(url);else if(isIOS())window.location.href=url;else pdf.save(filename);setTimeout(()=>URL.revokeObjectURL(url),60000);if(btn)btn.textContent='PDF creado ✓';if(pb)pb.textContent='PDF creado ✓';setTimeout(()=>{if(btn){btn.disabled=false;btn.textContent='Crear PDF';}if(pb){pb.disabled=false;pb.textContent='Crear PDF';}},1800);
    }catch(err){console.error(err);try{viewer?.close();}catch(_){}if(btn){btn.disabled=false;btn.textContent='Crear PDF';}if(pb){pb.disabled=false;pb.textContent='Crear PDF';}alert('No se pudo crear el PDF: '+(err?.message||'error desconocido'));}
  }
  window.mxCreatePdfNative=createPdf;

  async function boot(){await loadDependencies();installStyles();installPreview();const b=$('pdfBtn');if(b){b.textContent='Crear PDF';b.title='Genera el informe PDF sin alertas de mantención';}loadJsPDF().catch(()=>{});document.addEventListener('click',e=>{const x=e.target?.closest?.('#pdfBtn');if(!x)return;e.preventDefault();e.stopPropagation();window.mxCreatePdfNative();},true);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
